app.name=BLINK MATCH MEMORY
app.version=1.0.2
# Developer 1
app.1.name=April Marie S. Lasaca
app.1.github=
app.1.contribution=Asset Creation, Technical Writer

# Developer 2
app.2.name=Clarenz Ken M. Tatierra
app.2.github=
app.2.contribution=UI management, Debugging, Pause Menu, Weather System, Timer, Highscore tracking

# Developer 3
app.3.name=Angel B. Daclizon
app.3.github=
app.3.contribution=Asset Creation, Technical Writer

# Developer 4
app.4.name=Roswell Benedict Magallanes
app.4.github=mags123nice
app.4.contribution=Grid Building, Card Matching System, Shuffle System