app.name=BLINK MATCH MEMORY
app.version=1.0.2
# Developer 1
dev.1.name=April Marie S. Lasaca
dev.1.github=prilalalasaca
dev.1.contribution=Asset Creation, Technical Writer
dev.1.image=resources/images/Lasaca.png

# Developer 2
dev.2.name=Clarenz Ken M. Tatierra
dev.2.github=PendraKen519
dev.2.contribution=UI management, Debugging, Pause Menu, Weather System, Timer, Highscore tracking
dev.2.image=resources/images/Tatierra.png

# Developer 3
dev.3.name=Angel B. Daclizon
dev.3.github=abdaclizon-stack
dev.3.contribution=Asset Creation, Technical Writer
dev.3.image=resources/images/Daclizon.png

# Developer 4
dev.4.name=Roswell Benedict Magallanes
dev.4.github=mags123nice
dev.4.contribution=Grid Building, Card Matching System, Shuffle System
dev.4.image=resources/images/Magallanes.png